CREATE TABLE FORWIZ_POSITION_TB (	
       POS_CODE VARCHAR2(20) NOT NULL
       , POS_NAME VARCHAR2(30) NOT NULL
       , POS_COMMENT	VARCHAR2(100)
       , CONSTRAINT FORWIZ_POS_PK PRIMARY KEY (POS_CODE)	
);	

CREATE TABLE FORWIZ_DEPT_TB (	
       DEPT_CODE VARCHAR2(20) NOT NULL	
       , DEPT_NAME      VARCHAR2(30) NOT NULL
       , DEPT_COMMENT	VARCHAR2(100)
       , CONSTRAINT FORWIZ_DEPT_PK PRIMARY KEY (DEPT_CODE)	
);	

CREATE TABLE FORWIZ_COMMONCODE_TB(
	C_CODE	VARCHAR2(20)	NOT NULL
	, C_NAME	VARCHAR2(30)	NOT NULL
	, C_COMMENT	VARCHAR2(100)
	, CONSTRAINT FORWIZ_COMMONCODE_PK PRIMARY KEY (C_CODE)	
);
commit



INSERT INTO FORWIZ_POSITION_TB(POS_CODE, POS_NAME)
SELECT 'P01' AS POS_CODE, '사원' AS POS_NAME FROM DUAL
UNION ALL
SELECT 'P02' AS POS_CODE, '주임' AS POS_NAME FROM DUAL
UNION ALL
SELECT 'P03' AS POS_CODE, '대리' AS POS_NAME FROM DUAL
UNION ALL
SELECT 'P04' AS POS_CODE, '과장' AS POS_NAME FROM DUAL
UNION ALL
SELECT 'P05' AS POS_CODE, '차장' AS POS_NAME FROM DUAL
UNION ALL
SELECT 'P06' AS POS_CODE, '부장' AS POS_NAME FROM DUAL
UNION ALL
SELECT 'P07' AS POS_CODE, '본부장' AS POS_NAME FROM DUAL
UNION ALL
SELECT 'P08' AS POS_CODE, '전무' AS POS_NAME FROM DUAL
UNION ALL
SELECT 'P09' AS POS_CODE, '부사장' AS POS_NAME FROM DUAL
UNION ALL
SELECT 'P10' AS POS_CODE, '대표이사' AS POS_NAME FROM DUAL
;
COMMIT



SELECT * FROM FORWIZ_POSITION_TB;

INSERT INTO FORWIZ_DEPT_TB(DEPT_CODE, DEPT_NAME)
SELECT 'D01' AS DEPT_CODE, '경영지원팀' AS DEPT_NAME FROM DUAL
UNION ALL
SELECT 'D02' AS DEPT_CODE, '부설연구소' AS DEPT_NAME FROM DUAL
UNION ALL
SELECT 'D03' AS DEPT_CODE, 'SI사업1팀' AS DEPT_NAME FROM DUAL
UNION ALL
SELECT 'D04' AS DEPT_CODE, 'SI사업2팀' AS DEPT_NAME FROM DUAL
UNION ALL
SELECT 'D05' AS DEPT_CODE, 'SI사업3팀' AS DEPT_NAME FROM DUAL
UNION ALL
SELECT 'D06' AS DEPT_CODE, 'SI사업4팀' AS DEPT_NAME FROM DUAL
UNION ALL
SELECT 'D07' AS DEPT_CODE, 'SI사업본부' AS DEPT_NAME FROM DUAL
UNION ALL
SELECT 'D08' AS DEPT_CODE, '전략사업본부' AS DEPT_NAME FROM DUAL
UNION ALL
SELECT 'D09' AS DEPT_CODE, '경영지원본부' AS DEPT_NAME FROM DUAL
UNION ALL
SELECT 'D10' AS DEPT_CODE, '대표이사' AS DEPT_NAME FROM DUAL
;
COMMIT


INSERT INTO FORWIZ_COMMONCODE_TB(C_CODE,C_NAME)
SELECT 'GENDER_MALE' AS C_CODE, '남자' AS C_NAME FROM DUAL
UNION ALL
SELECT 'GENDER_FEMALE' AS C_CODE, '여자' AS C_NAME FROM DUAL
UNION ALL
SELECT 'AUTH_NORMAL' AS C_CODE, '일반사원' AS C_NAME FROM DUAL
UNION ALL
SELECT 'AUTH_ADMIN' AS C_CODE, '관리자' AS C_NAME FROM DUAL
;
COMMIT

