DROP TABLE FORWIZ_USER_TB;
DROP TABLE FORWIZ_POSITION_TB;
DROP TABLE FORWIZ_DEPT_TB;
DROP TABLE FORWIZ_COMMONCODE_TB;

CREATE TABLE FORWIZ_USER_TB (	
       USER_EMPNO    VARCHAR2(6)  NOT NULL,	
       USER_PASSWD 	 VARCHAR2(15),
       USER_NAME     VARCHAR2(15) NOT NULL,	
       USER_ADDR     VARCHAR2(100),
       USER_BIRTH    VARCHAR2(20) NOT NULL,	
       GEN_CODE      VARCHAR2(20) NOT NULL,  	
       USER_JOINDT   VARCHAR2(20) NOT NULL,	
       USER_PHONE    VARCHAR2(13),
       USER_TEL      VARCHAR2(13),
       DEPT_CODE     VARCHAR2(20) NOT NULL,	
       POS_CODE      VARCHAR2(20) NOT NULL,	
       USER_EMAIL    VARCHAR2(50),
       ADMIN_CODE    VARCHAR2(20),	
    	
      CONSTRAINT FORWIZ_USER_PK PRIMARY KEY (USER_EMPNO),	
      CONSTRAINT FORWIZ_USER_FK_DEPT FOREIGN KEY (DEPT_CODE) REFERENCES FORWIZ_DEPT_TB(DEPT_CODE),	
      CONSTRAINT FORWIZ_USER_FK_POS FOREIGN KEY (POS_CODE) REFERENCES FORWIZ_POSITION_TB(POS_CODE)	
);
commit

select * from forwiz_user_tb;